Space extension first pass
microsoft/makecode-minecraft-space pull request #1
Opened 2023-10-02 20:50 UTC by srietkerk

2023-10-02 21:05 UTC, jwunderl commented on icon.png
This file should be shrunk to ~100-500kb

2023-10-04 17:04 UTC, riknoll requested changes
Restore the contributing and trademark sections in the README!

Also, doesn't have to be this PR but you need to add docs and JSDoc comments for all of the functions

2023-10-04 17:04 UTC, riknoll commented on planets.ts
> +    //% blockId=space_solarsystem block="solar system at center $center=minecraftCreatePosition || of scale $scale"
```suggestion
    //% blockId=space_solarsystem block="solar system at center $center|| of scale $scale"
    //% center.shadow=minecraftCreatePosition
```

2023-10-04 17:04 UTC, riknoll commented on planets.ts
> +    //% blockId=space_planet_mercury block="mercury at center $center=minecraftCreatePosition || of radius $radius"
```suggestion
    //% blockId=space_planet_mercury block="mercury at center $center|| of radius $radius"
    //% center.shadow=minecraftCreatePosition
```

2023-10-04 17:04 UTC, riknoll commented on planets.ts
> +    //% blockId=space_planet_venus block="venus at center $center=minecraftCreatePosition || of radius $radius"
```suggestion
    //% blockId=space_planet_venus block="venus at center $center|| of radius $radius"
    //% center.shadow=minecraftCreatePosition
```

2023-10-04 17:04 UTC, riknoll commented on planets.ts
> +    //% blockId=space_planet_earth block="earth at center $center=minecraftCreatePosition || of radius $radius"
```suggestion
    //% blockId=space_planet_earth block="earth at center $center|| of radius $radius"
    //% center.shadow=minecraftCreatePosition
```

2023-10-04 17:04 UTC, riknoll commented on planets.ts
> +    //% blockId=space_planet_mars block="mars at center $center=minecraftCreatePosition || of radius $radius"
```suggestion
    //% blockId=space_planet_mars block="mars at center $center|| of radius $radius"
    //% center.shadow=minecraftCreatePosition
```

2023-10-04 17:04 UTC, riknoll commented on planets.ts
> +    //% blockId=space_planet_jupiter block="jupiter at center $center=minecraftCreatePosition || of radius $radius"
```suggestion
    //% blockId=space_planet_jupiter block="jupiter at center $center|| of radius $radius"
    //% center.shadow=minecraftCreatePosition
```

2023-10-04 17:04 UTC, riknoll commented on planets.ts
> +    //% blockId=space_planet_saturn block="saturn at center $center=minecraftCreatePosition || of radius $radius"
```suggestion
    //% blockId=space_planet_saturn block="saturn at center $center|| of radius $radius"
    //% center.shadow=minecraftCreatePosition
```

2023-10-04 17:04 UTC, riknoll commented on planets.ts
> +    //% blockId=space_planet_uranus block="uranus at center $center=minecraftCreatePosition || of radius $radius"
```suggestion
    //% blockId=space_planet_uranus block="uranus at center $center|| of radius $radius"
    //% center.shadow=minecraftCreatePosition
```

2023-10-04 17:04 UTC, riknoll commented on planets.ts
> +    //% blockId=space_planet_neptune block="neptune at center $center=minecraftCreatePosition || of radius $radius"
```suggestion
    //% blockId=space_planet_neptune block="neptune at center $center|| of radius $radius"
    //% center.shadow=minecraftCreatePosition
```

2023-10-04 17:04 UTC, riknoll commented on planets.ts
> +    //% blockId=space_stars_sun block="sun at center $center=minecraftCreatePosition || of radius $radius"
```suggestion
    //% blockId=space_stars_sun block="sun at center $center|| of radius $radius"
    //% center.shadow=minecraftCreatePosition
```

2023-10-04 17:04 UTC, riknoll commented on sphere.ts
> +    //% block="sphere of random blocks from $blockList|center $center=minecraftCreatePosition|radius $radius|$operator"
```suggestion
    //% block="sphere of random blocks from $blockList|center $center|radius $radius|$operator"
    //% center.shadow=minecraftCreatePosition
```

2023-10-04 17:04 UTC, riknoll commented on sphere.ts
> +    //% block="sphere of random layers from $blockList|center $center=minecraftCreatePosition|radius $radius|around $orientation|in order of blocks $useBlockOrder|$operator"
```suggestion
    //% block="sphere of random layers from $blockList|center $center|radius $radius|around $orientation|in order of blocks $useBlockOrder|$operator"
    //% center.shadow=minecraftCreatePosition
```

2023-10-04 17:04 UTC, riknoll commented on README.md
> +This repository is an approved **extension** in Makecode for Minecraft Education.
```suggestion
This repository is an approved **extension** in Microsoft MakeCode for Minecraft Education. 
```

2023-10-04 18:53 UTC, riknoll approved these changes

2023-10-05 17:35 UTC, merged